
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.3)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _Tblbill_items
	Inherits SqlClientEntity

		Public Sub New() 
			Me.QuerySource = "Tblbill_items"
			Me.MappingName = "Tblbill_items"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_Tblbill_itemsLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
	Public Overridable Function LoadByPrimaryKey(ByVal Id As Integer) As Boolean

		Dim parameters As ListDictionary = New ListDictionary()
		parameters.Add(_Tblbill_items.Parameters.Id, Id)

		
		Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_Tblbill_itemsLoadByPrimaryKey]", parameters)

	End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property Id As SqlParameter
			Get
				Return New SqlParameter("@Id", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Item_id As SqlParameter
			Get
				Return New SqlParameter("@Item_id", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Qty As SqlParameter
			Get
				Return New SqlParameter("@Qty", SqlDbType.Decimal, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Rates As SqlParameter
			Get
				Return New SqlParameter("@Rates", SqlDbType.Decimal, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Billid As SqlParameter
			Get
				Return New SqlParameter("@Billid", SqlDbType.Int, 0)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const Id As String = "id"
        Public Const Item_id As String = "item_id"
        Public Const Qty As String = "qty"
        Public Const Rates As String = "Rates"
        Public Const Billid As String = "billid"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(Id) = _Tblbill_items.PropertyNames.Id
				ht(Item_id) = _Tblbill_items.PropertyNames.Item_id
				ht(Qty) = _Tblbill_items.PropertyNames.Qty
				ht(Rates) = _Tblbill_items.PropertyNames.Rates
				ht(Billid) = _Tblbill_items.PropertyNames.Billid

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const Id As String = "Id"
        Public Const Item_id As String = "Item_id"
        Public Const Qty As String = "Qty"
        Public Const Rates As String = "Rates"
        Public Const Billid As String = "Billid"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(Id) = _Tblbill_items.ColumnNames.Id
				ht(Item_id) = _Tblbill_items.ColumnNames.Item_id
				ht(Qty) = _Tblbill_items.ColumnNames.Qty
				ht(Rates) = _Tblbill_items.ColumnNames.Rates
				ht(Billid) = _Tblbill_items.ColumnNames.Billid

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const Id As String = "s_Id"
        Public Const Item_id As String = "s_Item_id"
        Public Const Qty As String = "s_Qty"
        Public Const Rates As String = "s_Rates"
        Public Const Billid As String = "s_Billid"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property Id As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.Id)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.Id, Value)
			End Set
		End Property

		Public Overridable Property Item_id As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.Item_id)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.Item_id, Value)
			End Set
		End Property

		Public Overridable Property Qty As Decimal
			Get
				Return MyBase.GetDecimal(ColumnNames.Qty)
			End Get
			Set(ByVal Value As Decimal)
				MyBase.SetDecimal(ColumnNames.Qty, Value)
			End Set
		End Property

		Public Overridable Property Rates As Decimal
			Get
				Return MyBase.GetDecimal(ColumnNames.Rates)
			End Get
			Set(ByVal Value As Decimal)
				MyBase.SetDecimal(ColumnNames.Rates, Value)
			End Set
		End Property

		Public Overridable Property Billid As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.Billid)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.Billid, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_Id As String
			Get
				If Me.IsColumnNull(ColumnNames.Id) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.Id)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Id)
				Else
					Me.Id = MyBase.SetIntegerAsString(ColumnNames.Id, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Item_id As String
			Get
				If Me.IsColumnNull(ColumnNames.Item_id) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.Item_id)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Item_id)
				Else
					Me.Item_id = MyBase.SetIntegerAsString(ColumnNames.Item_id, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Qty As String
			Get
				If Me.IsColumnNull(ColumnNames.Qty) Then
					Return String.Empty
				Else
					Return MyBase.GetDecimalAsString(ColumnNames.Qty)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Qty)
				Else
					Me.Qty = MyBase.SetDecimalAsString(ColumnNames.Qty, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Rates As String
			Get
				If Me.IsColumnNull(ColumnNames.Rates) Then
					Return String.Empty
				Else
					Return MyBase.GetDecimalAsString(ColumnNames.Rates)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Rates)
				Else
					Me.Rates = MyBase.SetDecimalAsString(ColumnNames.Rates, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Billid As String
			Get
				If Me.IsColumnNull(ColumnNames.Billid) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.Billid)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Billid)
				Else
					Me.Billid = MyBase.SetIntegerAsString(ColumnNames.Billid, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property Id() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Id, Parameters.Id)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Item_id() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Item_id, Parameters.Item_id)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Qty() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Qty, Parameters.Qty)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Rates() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Rates, Parameters.Rates)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Billid() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Billid, Parameters.Billid)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property Id() As WhereParameter 
			Get
				If _Id_W Is Nothing Then
					_Id_W = TearOff.Id
				End If
				Return _Id_W
			End Get
		End Property

		Public ReadOnly Property Item_id() As WhereParameter 
			Get
				If _Item_id_W Is Nothing Then
					_Item_id_W = TearOff.Item_id
				End If
				Return _Item_id_W
			End Get
		End Property

		Public ReadOnly Property Qty() As WhereParameter 
			Get
				If _Qty_W Is Nothing Then
					_Qty_W = TearOff.Qty
				End If
				Return _Qty_W
			End Get
		End Property

		Public ReadOnly Property Rates() As WhereParameter 
			Get
				If _Rates_W Is Nothing Then
					_Rates_W = TearOff.Rates
				End If
				Return _Rates_W
			End Get
		End Property

		Public ReadOnly Property Billid() As WhereParameter 
			Get
				If _Billid_W Is Nothing Then
					_Billid_W = TearOff.Billid
				End If
				Return _Billid_W
			End Get
		End Property

		Private _Id_W As WhereParameter = Nothing
		Private _Item_id_W As WhereParameter = Nothing
		Private _Qty_W As WhereParameter = Nothing
		Private _Rates_W As WhereParameter = Nothing
		Private _Billid_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_Id_W = Nothing
			_Item_id_W = Nothing
			_Qty_W = Nothing
			_Rates_W = Nothing
			_Billid_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property Id() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Id, Parameters.Id)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Item_id() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Item_id, Parameters.Item_id)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Qty() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Qty, Parameters.Qty)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Rates() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Rates, Parameters.Rates)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Billid() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Billid, Parameters.Billid)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property Id() As AggregateParameter 
			Get
				If _Id_W Is Nothing Then
					_Id_W = TearOff.Id
				End If
				Return _Id_W
			End Get
		End Property

		Public ReadOnly Property Item_id() As AggregateParameter 
			Get
				If _Item_id_W Is Nothing Then
					_Item_id_W = TearOff.Item_id
				End If
				Return _Item_id_W
			End Get
		End Property

		Public ReadOnly Property Qty() As AggregateParameter 
			Get
				If _Qty_W Is Nothing Then
					_Qty_W = TearOff.Qty
				End If
				Return _Qty_W
			End Get
		End Property

		Public ReadOnly Property Rates() As AggregateParameter 
			Get
				If _Rates_W Is Nothing Then
					_Rates_W = TearOff.Rates
				End If
				Return _Rates_W
			End Get
		End Property

		Public ReadOnly Property Billid() As AggregateParameter 
			Get
				If _Billid_W Is Nothing Then
					_Billid_W = TearOff.Billid
				End If
				Return _Billid_W
			End Get
		End Property

		Private _Id_W As AggregateParameter = Nothing
		Private _Item_id_W As AggregateParameter = Nothing
		Private _Qty_W As AggregateParameter = Nothing
		Private _Rates_W As AggregateParameter = Nothing
		Private _Billid_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_Id_W = Nothing
		_Item_id_W = Nothing
		_Qty_W = Nothing
		_Rates_W = Nothing
		_Billid_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_Tblbill_itemsInsert]" 
	    
		CreateParameters(cmd)
		
		Dim p As SqlParameter
		p = cmd.Parameters(Parameters.Id.ParameterName)
		p.Direction = ParameterDirection.Output
    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_Tblbill_itemsUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_Tblbill_itemsDelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.Id)
		p.SourceColumn = ColumnNames.Id
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.Id)
		p.SourceColumn = ColumnNames.Id
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Item_id)
		p.SourceColumn = ColumnNames.Item_id
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Qty)
		p.SourceColumn = ColumnNames.Qty
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Rates)
		p.SourceColumn = ColumnNames.Rates
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Billid)
		p.SourceColumn = ColumnNames.Billid
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

