
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.3)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _Tblcompany_master
	Inherits SqlClientEntity

		Public Sub New() 
			Me.QuerySource = "Tblcompany_master"
			Me.MappingName = "Tblcompany_master"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_Tblcompany_masterLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
	Public Overridable Function LoadByPrimaryKey(ByVal Id As Integer) As Boolean

		Dim parameters As ListDictionary = New ListDictionary()
		parameters.Add(_Tblcompany_master.Parameters.Id, Id)

		
		Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_Tblcompany_masterLoadByPrimaryKey]", parameters)

	End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property Id As SqlParameter
			Get
				Return New SqlParameter("@Id", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Name As SqlParameter
			Get
				Return New SqlParameter("@Name", SqlDbType.VarChar, 255)
			End Get
		End Property
		
		Public Shared ReadOnly Property Address As SqlParameter
			Get
				Return New SqlParameter("@Address", SqlDbType.VarChar, 255)
			End Get
		End Property
		
		Public Shared ReadOnly Property Description As SqlParameter
			Get
				Return New SqlParameter("@Description", SqlDbType.VarChar, 255)
			End Get
		End Property
		
		Public Shared ReadOnly Property Vat_tin_no As SqlParameter
			Get
				Return New SqlParameter("@Vat_tin_no", SqlDbType.VarChar, 100)
			End Get
		End Property
		
		Public Shared ReadOnly Property Cst_tin_no As SqlParameter
			Get
				Return New SqlParameter("@Cst_tin_no", SqlDbType.VarChar, 100)
			End Get
		End Property
		
		Public Shared ReadOnly Property Phoneno As SqlParameter
			Get
				Return New SqlParameter("@Phoneno", SqlDbType.VarChar, 50)
			End Get
		End Property
		
		Public Shared ReadOnly Property Vat As SqlParameter
			Get
				Return New SqlParameter("@Vat", SqlDbType.Decimal, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Add_tax As SqlParameter
			Get
				Return New SqlParameter("@Add_tax", SqlDbType.Decimal, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Type As SqlParameter
			Get
				Return New SqlParameter("@Type", SqlDbType.VarChar, 50)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const Id As String = "id"
        Public Const Name As String = "name"
        Public Const Address As String = "address"
        Public Const Description As String = "description"
        Public Const Vat_tin_no As String = "vat_tin_no"
        Public Const Cst_tin_no As String = "cst_tin_no"
        Public Const Phoneno As String = "phoneno"
        Public Const Vat As String = "vat"
        Public Const Add_tax As String = "add_tax"
        Public Const Type As String = "type"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(Id) = _Tblcompany_master.PropertyNames.Id
				ht(Name) = _Tblcompany_master.PropertyNames.Name
				ht(Address) = _Tblcompany_master.PropertyNames.Address
				ht(Description) = _Tblcompany_master.PropertyNames.Description
				ht(Vat_tin_no) = _Tblcompany_master.PropertyNames.Vat_tin_no
				ht(Cst_tin_no) = _Tblcompany_master.PropertyNames.Cst_tin_no
				ht(Phoneno) = _Tblcompany_master.PropertyNames.Phoneno
				ht(Vat) = _Tblcompany_master.PropertyNames.Vat
				ht(Add_tax) = _Tblcompany_master.PropertyNames.Add_tax
				ht(Type) = _Tblcompany_master.PropertyNames.Type

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const Id As String = "Id"
        Public Const Name As String = "Name"
        Public Const Address As String = "Address"
        Public Const Description As String = "Description"
        Public Const Vat_tin_no As String = "Vat_tin_no"
        Public Const Cst_tin_no As String = "Cst_tin_no"
        Public Const Phoneno As String = "Phoneno"
        Public Const Vat As String = "Vat"
        Public Const Add_tax As String = "Add_tax"
        Public Const Type As String = "Type"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(Id) = _Tblcompany_master.ColumnNames.Id
				ht(Name) = _Tblcompany_master.ColumnNames.Name
				ht(Address) = _Tblcompany_master.ColumnNames.Address
				ht(Description) = _Tblcompany_master.ColumnNames.Description
				ht(Vat_tin_no) = _Tblcompany_master.ColumnNames.Vat_tin_no
				ht(Cst_tin_no) = _Tblcompany_master.ColumnNames.Cst_tin_no
				ht(Phoneno) = _Tblcompany_master.ColumnNames.Phoneno
				ht(Vat) = _Tblcompany_master.ColumnNames.Vat
				ht(Add_tax) = _Tblcompany_master.ColumnNames.Add_tax
				ht(Type) = _Tblcompany_master.ColumnNames.Type

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const Id As String = "s_Id"
        Public Const Name As String = "s_Name"
        Public Const Address As String = "s_Address"
        Public Const Description As String = "s_Description"
        Public Const Vat_tin_no As String = "s_Vat_tin_no"
        Public Const Cst_tin_no As String = "s_Cst_tin_no"
        Public Const Phoneno As String = "s_Phoneno"
        Public Const Vat As String = "s_Vat"
        Public Const Add_tax As String = "s_Add_tax"
        Public Const Type As String = "s_Type"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property Id As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.Id)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.Id, Value)
			End Set
		End Property

		Public Overridable Property Name As String
			Get
				Return MyBase.GetString(ColumnNames.Name)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Name, Value)
			End Set
		End Property

		Public Overridable Property Address As String
			Get
				Return MyBase.GetString(ColumnNames.Address)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Address, Value)
			End Set
		End Property

		Public Overridable Property Description As String
			Get
				Return MyBase.GetString(ColumnNames.Description)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Description, Value)
			End Set
		End Property

		Public Overridable Property Vat_tin_no As String
			Get
				Return MyBase.GetString(ColumnNames.Vat_tin_no)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Vat_tin_no, Value)
			End Set
		End Property

		Public Overridable Property Cst_tin_no As String
			Get
				Return MyBase.GetString(ColumnNames.Cst_tin_no)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Cst_tin_no, Value)
			End Set
		End Property

		Public Overridable Property Phoneno As String
			Get
				Return MyBase.GetString(ColumnNames.Phoneno)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Phoneno, Value)
			End Set
		End Property

		Public Overridable Property Vat As Decimal
			Get
				Return MyBase.GetDecimal(ColumnNames.Vat)
			End Get
			Set(ByVal Value As Decimal)
				MyBase.SetDecimal(ColumnNames.Vat, Value)
			End Set
		End Property

		Public Overridable Property Add_tax As Decimal
			Get
				Return MyBase.GetDecimal(ColumnNames.Add_tax)
			End Get
			Set(ByVal Value As Decimal)
				MyBase.SetDecimal(ColumnNames.Add_tax, Value)
			End Set
		End Property

		Public Overridable Property Type As String
			Get
				Return MyBase.GetString(ColumnNames.Type)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Type, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_Id As String
			Get
				If Me.IsColumnNull(ColumnNames.Id) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.Id)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Id)
				Else
					Me.Id = MyBase.SetIntegerAsString(ColumnNames.Id, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Name As String
			Get
				If Me.IsColumnNull(ColumnNames.Name) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Name)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Name)
				Else
					Me.Name = MyBase.SetStringAsString(ColumnNames.Name, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Address As String
			Get
				If Me.IsColumnNull(ColumnNames.Address) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Address)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Address)
				Else
					Me.Address = MyBase.SetStringAsString(ColumnNames.Address, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Description As String
			Get
				If Me.IsColumnNull(ColumnNames.Description) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Description)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Description)
				Else
					Me.Description = MyBase.SetStringAsString(ColumnNames.Description, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Vat_tin_no As String
			Get
				If Me.IsColumnNull(ColumnNames.Vat_tin_no) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Vat_tin_no)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Vat_tin_no)
				Else
					Me.Vat_tin_no = MyBase.SetStringAsString(ColumnNames.Vat_tin_no, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Cst_tin_no As String
			Get
				If Me.IsColumnNull(ColumnNames.Cst_tin_no) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Cst_tin_no)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Cst_tin_no)
				Else
					Me.Cst_tin_no = MyBase.SetStringAsString(ColumnNames.Cst_tin_no, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Phoneno As String
			Get
				If Me.IsColumnNull(ColumnNames.Phoneno) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Phoneno)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Phoneno)
				Else
					Me.Phoneno = MyBase.SetStringAsString(ColumnNames.Phoneno, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Vat As String
			Get
				If Me.IsColumnNull(ColumnNames.Vat) Then
					Return String.Empty
				Else
					Return MyBase.GetDecimalAsString(ColumnNames.Vat)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Vat)
				Else
					Me.Vat = MyBase.SetDecimalAsString(ColumnNames.Vat, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Add_tax As String
			Get
				If Me.IsColumnNull(ColumnNames.Add_tax) Then
					Return String.Empty
				Else
					Return MyBase.GetDecimalAsString(ColumnNames.Add_tax)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Add_tax)
				Else
					Me.Add_tax = MyBase.SetDecimalAsString(ColumnNames.Add_tax, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Type As String
			Get
				If Me.IsColumnNull(ColumnNames.Type) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Type)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Type)
				Else
					Me.Type = MyBase.SetStringAsString(ColumnNames.Type, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property Id() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Id, Parameters.Id)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Name() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Name, Parameters.Name)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Address() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Address, Parameters.Address)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Description() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Description, Parameters.Description)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Vat_tin_no() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Vat_tin_no, Parameters.Vat_tin_no)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Cst_tin_no() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Cst_tin_no, Parameters.Cst_tin_no)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Phoneno() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Phoneno, Parameters.Phoneno)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Vat() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Vat, Parameters.Vat)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Add_tax() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Add_tax, Parameters.Add_tax)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Type() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Type, Parameters.Type)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property Id() As WhereParameter 
			Get
				If _Id_W Is Nothing Then
					_Id_W = TearOff.Id
				End If
				Return _Id_W
			End Get
		End Property

		Public ReadOnly Property Name() As WhereParameter 
			Get
				If _Name_W Is Nothing Then
					_Name_W = TearOff.Name
				End If
				Return _Name_W
			End Get
		End Property

		Public ReadOnly Property Address() As WhereParameter 
			Get
				If _Address_W Is Nothing Then
					_Address_W = TearOff.Address
				End If
				Return _Address_W
			End Get
		End Property

		Public ReadOnly Property Description() As WhereParameter 
			Get
				If _Description_W Is Nothing Then
					_Description_W = TearOff.Description
				End If
				Return _Description_W
			End Get
		End Property

		Public ReadOnly Property Vat_tin_no() As WhereParameter 
			Get
				If _Vat_tin_no_W Is Nothing Then
					_Vat_tin_no_W = TearOff.Vat_tin_no
				End If
				Return _Vat_tin_no_W
			End Get
		End Property

		Public ReadOnly Property Cst_tin_no() As WhereParameter 
			Get
				If _Cst_tin_no_W Is Nothing Then
					_Cst_tin_no_W = TearOff.Cst_tin_no
				End If
				Return _Cst_tin_no_W
			End Get
		End Property

		Public ReadOnly Property Phoneno() As WhereParameter 
			Get
				If _Phoneno_W Is Nothing Then
					_Phoneno_W = TearOff.Phoneno
				End If
				Return _Phoneno_W
			End Get
		End Property

		Public ReadOnly Property Vat() As WhereParameter 
			Get
				If _Vat_W Is Nothing Then
					_Vat_W = TearOff.Vat
				End If
				Return _Vat_W
			End Get
		End Property

		Public ReadOnly Property Add_tax() As WhereParameter 
			Get
				If _Add_tax_W Is Nothing Then
					_Add_tax_W = TearOff.Add_tax
				End If
				Return _Add_tax_W
			End Get
		End Property

		Public ReadOnly Property Type() As WhereParameter 
			Get
				If _Type_W Is Nothing Then
					_Type_W = TearOff.Type
				End If
				Return _Type_W
			End Get
		End Property

		Private _Id_W As WhereParameter = Nothing
		Private _Name_W As WhereParameter = Nothing
		Private _Address_W As WhereParameter = Nothing
		Private _Description_W As WhereParameter = Nothing
		Private _Vat_tin_no_W As WhereParameter = Nothing
		Private _Cst_tin_no_W As WhereParameter = Nothing
		Private _Phoneno_W As WhereParameter = Nothing
		Private _Vat_W As WhereParameter = Nothing
		Private _Add_tax_W As WhereParameter = Nothing
		Private _Type_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_Id_W = Nothing
			_Name_W = Nothing
			_Address_W = Nothing
			_Description_W = Nothing
			_Vat_tin_no_W = Nothing
			_Cst_tin_no_W = Nothing
			_Phoneno_W = Nothing
			_Vat_W = Nothing
			_Add_tax_W = Nothing
			_Type_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property Id() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Id, Parameters.Id)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Name() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Name, Parameters.Name)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Address() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Address, Parameters.Address)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Description() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Description, Parameters.Description)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Vat_tin_no() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Vat_tin_no, Parameters.Vat_tin_no)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Cst_tin_no() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Cst_tin_no, Parameters.Cst_tin_no)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Phoneno() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Phoneno, Parameters.Phoneno)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Vat() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Vat, Parameters.Vat)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Add_tax() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Add_tax, Parameters.Add_tax)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Type() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Type, Parameters.Type)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property Id() As AggregateParameter 
			Get
				If _Id_W Is Nothing Then
					_Id_W = TearOff.Id
				End If
				Return _Id_W
			End Get
		End Property

		Public ReadOnly Property Name() As AggregateParameter 
			Get
				If _Name_W Is Nothing Then
					_Name_W = TearOff.Name
				End If
				Return _Name_W
			End Get
		End Property

		Public ReadOnly Property Address() As AggregateParameter 
			Get
				If _Address_W Is Nothing Then
					_Address_W = TearOff.Address
				End If
				Return _Address_W
			End Get
		End Property

		Public ReadOnly Property Description() As AggregateParameter 
			Get
				If _Description_W Is Nothing Then
					_Description_W = TearOff.Description
				End If
				Return _Description_W
			End Get
		End Property

		Public ReadOnly Property Vat_tin_no() As AggregateParameter 
			Get
				If _Vat_tin_no_W Is Nothing Then
					_Vat_tin_no_W = TearOff.Vat_tin_no
				End If
				Return _Vat_tin_no_W
			End Get
		End Property

		Public ReadOnly Property Cst_tin_no() As AggregateParameter 
			Get
				If _Cst_tin_no_W Is Nothing Then
					_Cst_tin_no_W = TearOff.Cst_tin_no
				End If
				Return _Cst_tin_no_W
			End Get
		End Property

		Public ReadOnly Property Phoneno() As AggregateParameter 
			Get
				If _Phoneno_W Is Nothing Then
					_Phoneno_W = TearOff.Phoneno
				End If
				Return _Phoneno_W
			End Get
		End Property

		Public ReadOnly Property Vat() As AggregateParameter 
			Get
				If _Vat_W Is Nothing Then
					_Vat_W = TearOff.Vat
				End If
				Return _Vat_W
			End Get
		End Property

		Public ReadOnly Property Add_tax() As AggregateParameter 
			Get
				If _Add_tax_W Is Nothing Then
					_Add_tax_W = TearOff.Add_tax
				End If
				Return _Add_tax_W
			End Get
		End Property

		Public ReadOnly Property Type() As AggregateParameter 
			Get
				If _Type_W Is Nothing Then
					_Type_W = TearOff.Type
				End If
				Return _Type_W
			End Get
		End Property

		Private _Id_W As AggregateParameter = Nothing
		Private _Name_W As AggregateParameter = Nothing
		Private _Address_W As AggregateParameter = Nothing
		Private _Description_W As AggregateParameter = Nothing
		Private _Vat_tin_no_W As AggregateParameter = Nothing
		Private _Cst_tin_no_W As AggregateParameter = Nothing
		Private _Phoneno_W As AggregateParameter = Nothing
		Private _Vat_W As AggregateParameter = Nothing
		Private _Add_tax_W As AggregateParameter = Nothing
		Private _Type_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_Id_W = Nothing
		_Name_W = Nothing
		_Address_W = Nothing
		_Description_W = Nothing
		_Vat_tin_no_W = Nothing
		_Cst_tin_no_W = Nothing
		_Phoneno_W = Nothing
		_Vat_W = Nothing
		_Add_tax_W = Nothing
		_Type_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_Tblcompany_masterInsert]" 
	    
		CreateParameters(cmd)
		
		Dim p As SqlParameter
		p = cmd.Parameters(Parameters.Id.ParameterName)
		p.Direction = ParameterDirection.Output
    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_Tblcompany_masterUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_Tblcompany_masterDelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.Id)
		p.SourceColumn = ColumnNames.Id
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.Id)
		p.SourceColumn = ColumnNames.Id
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Name)
		p.SourceColumn = ColumnNames.Name
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Address)
		p.SourceColumn = ColumnNames.Address
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Description)
		p.SourceColumn = ColumnNames.Description
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Vat_tin_no)
		p.SourceColumn = ColumnNames.Vat_tin_no
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Cst_tin_no)
		p.SourceColumn = ColumnNames.Cst_tin_no
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Phoneno)
		p.SourceColumn = ColumnNames.Phoneno
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Vat)
		p.SourceColumn = ColumnNames.Vat
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Add_tax)
		p.SourceColumn = ColumnNames.Add_tax
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Type)
		p.SourceColumn = ColumnNames.Type
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

