
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Tblcompany_master 
	Inherits _Tblcompany_master
    Public Function LoadgridData() As DataTable
        Dim strQuery As String = "SELECt * from tblcompany_master"
        MyBase.LoadFromRawSql(strQuery)
        Return MyBase.DefaultView.Table
    End Function
End Class
