
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Tbluser_master 
	Inherits _Tbluser_master
    
    Public Function LoadgridData(ByVal username As String, ByVal password As String) As Integer
        Dim strQuery As String = "select count(*) from tbluser_master where username='" + username + "' and password='" + password + "'"
        MyBase.LoadFromRawSql(strQuery)
        Return MyBase.DefaultView(0)(0)
    End Function
End Class
